#!/bin/sh -x

VERSION=$(curl -s 'https://api.github.com/repos/cli/cli/releases' | jq -r '.[0].tag_name' | sed -e 's/^v//')

GH_VERSION=${SET_VERSION:-$VERSION}

cat <<EOF > docker-bake.ci.hcl
variable "DOCKER_META_VERSION" { default="" }

group "default" {
    targets = ["ci_build"]
}

target "ci_build" {
  inherits = ["build", "docker-metadata-action"]
  tags = [
    "maniator/gh:v${GH_VERSION}",
    "maniator/gh:latest",
  ]
}
EOF

echo "::set-output name=gh_version::$GH_VERSION"
